const contactlist=[
    {
    Name:"حمید",
    Family:"حیدری",
    Email:"hamid.production@gmail.com",
    PhoneNumber:"09125501080",
    Id:1
},
{
    Name:"حسن",
    Family:"حیدری",
    Email:"hasan.production@gmail.com",
    PhoneNumber:"091222588508",
    Id:2
},
{
    Name:"اکبر",
    Family:"حیدری",
    Email:"akbar.production@gmail.com",
    PhoneNumber:"091352689631",
    Id:3
},
{
    Name:"احمد",
    Family:"حیدری",
    Email:"ahmad.production@gmail.com",
    PhoneNumber:"09124471236",
    Id:4
},
{
    Name:"یاسینٌ",
    Family:"حیدری",
    Email:"yasin.production@gmail.com",
    PhoneNumber:"09197247465",
    Id:5
}
]
export default contactlist;